### ISSUE TITLE
revise the explanations

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/politely#91]
# To-do's
- [ ] add `translate` step
- [ ] change  the nouns to verbs
- [ ] add `conjugate` step (just show before & after)
